# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/ros2_cam_nbdev',
                'doc_host': 'https://Ramon-PR.github.io',
                'git_url': 'https://github.com/Ramon-PR/ros2_cam_nbdev',
                'lib_path': 'ros2_cam_nbdev'},
  'syms': {}}
